#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# shellcheck disable=SC2086

if [[ "$CONF_TYPE" == "yaml" ]]; then
    exec \
        s6-setuidgid abc webhook \
        -hooks /config/hooks/hooks.yaml \
        -ip 0.0.0.0 ${EXTRA_PARAM:=-hotreload}
fi
if [[ "$CONF_TYPE" == "json" ]]; then
    exec \
        s6-setuidgid abc webhook \
        -hooks /config/hooks/hooks.json \
        -ip 0.0.0.0 ${EXTRA_PARAM:=-hotreload}
fi
